spring:
  profiles:
    active: production
csv:
  file-path: D:\Users\programmers\vouchermanager\src\main\java\org\prgrms\vouchermanager\Repository\blacklist.csv

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vouchermanager
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver